language: node_js
node_js:
  - "8"
deploy:
  provider: npm
  api_key: $NPMJS_ACCESS_TOKEN
  email: anissoftkun@gmail.com
  before_script:
    - npm install
    - npm build
  script: "cp .template.npmrc $HOME/.npmrc && npm publish"
  skip_cleanup: true
  on:
    branch: master
notifications:
  email:
    recipients:
    - anissoftkun@gmail.com
    on_success: change
    on_failure: always
